server:
  port: 8080
  servlet:
    context-path: /sample-sp

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: DEBUG
    sample: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
